version: "3.7"

services:
  mysql:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: abc
      MYSQL_PASSWORD: abc
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - default

  mongo:
    image: mongo
    volumes:
      - ./docker/mongo:/data
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default

networks:
  default:
    driver: bridge
