
const user = {
    accessFailedCount :0,
    address: "",
    avatar:"",
    birthday,
    dateLogin,
    deletedOn: null,
    email:"adminsite@gmail.com",
    fullname: "Admin Site",
    gender: 1,
    exploreField: 1  ,
    siteId: 1,
    positionId:1,
    infoManagementLevel:null,
    isLockoutEnabled : true,
    lockoutEndDate : null,
    passwordHash : "AQAAAAIAAYagAAAAEFwkvUkOhM2GpDB4DXa1MmKyLRpukZrolfwWQgYIsYJd//LFS0PlZI…",
    phone :"0906258989",
    pwd : "Unknown",
    securityStamp : "DVBXFQKRZQPEOWO3UED6S62SRXQMIXVQ",
    status : 1,
    timeUpdate : null,
    userName : "adminsite@gmail.com",
    listRoles  : null,
    listPolicy : null,
    role : "ADMIN",
    functionsTree : null,

}